#!/usr/bin/env ruby
def require_relative(required)
	require File.join(File.dirname(__FILE__), required)
end

require_relative 'lib/utils.rb'
require_relative 'lib/uploader.rb'
require_relative 'lib/downloader.rb'
require_relative 'lib/cli.rb'

#global constants
module Skyhook
		SKYHOOK_STORAGE_KEY = 'skyhook-storage'
end

if __FILE__ == $0 then
	Skyhook::Cli.new.run
end